FROM openjdk:17-jdk-slim

COPY target/*.jar /app/app.jar

WORKDIR /app

CMD ["java", "-jar", "app.jar"]

ENV NOTIFICATION_HUB_MONGO_HOST=$NOTIFICATION_HUB_MONGO_HOST
ENV NOTIFICATION_HUB_MONGO_PORT=NOTIFICATION_HUB_MONGO_PORT
ENV NOTIFICATION_HUB_MONGO_DATABASE=NOTIFICATION_HUB_MONGO_DATABASE
ENV NOTIFICATION_HUB_KAFKA_SERVERS=NOTIFICATION_HUB_KAFKA_SERVERS