version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: notifier_hub_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka-1:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka-1:29092,DOCKER_EXTERNAL://localhost:9092
      KAFKA_LISTENERS: DOCKER_INTERNAL://0.0.0.0:29092,DOCKER_EXTERNAL://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kafka-net


  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8085:9000
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: Notification_Hub_Cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:29092
      server.port: 9000
    depends_on:
      - kafka-1
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge

volumes:
  mongodb_data:
